# Generated by Django 4.1.2 on 2022-12-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='auth_provider',
        ),
    ]
