# Generated by Django 4.1.2 on 2022-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='short_title'),
        ),
    ]
