# Generated by Django 4.1.2 on 2022-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_prime',
            field=models.BooleanField(default=False),
        ),
    ]
